#!/bin/bash

pushd . &>/dev/null
cd $(dirname $0)

backup_dir=$(pwd)/backup
file_dir=$(pwd)/files

cp_num() {
  src=$1
  dest_dir=$2
  dest_name=$3
  if [[ -e $dest_dir/$dest_name ]] ; then
    i=0
    while [[ -e $dest_dir/$i-$dest_name ]] ; do
      let i++
    done
    dest_name=$i-$dest_name
  fi
  cp -a $src $dest_dir/$dest_name
}

replace() {
  filename=$1
  dest_dir=$2

  case "$#" in
    1)
      dest_dir=~
      ;;
    2)
      ;;
    *)
      exit 1
      ;;
  esac

  # Check the file exists
  if [ ! -f $file_dir/$filename ]; then
    echo "$filename not found!"
    exit 1
  fi

  # Remove old backup and create a new one
  cp_num $dest_dir/$filename $backup_dir $filename 2>/dev/null

  # Replace the old file with a symlink to the files
  rm $dest_dir/$filename 2>/dev/null
  ln -s $file_dir/$filename $dest_dir/$filename
}

case "$1" in
  --help|-h)
    echo "options:"
    exit 1
    ;;
esac

mkdir old &>/dev/null

while read -a p; do
  case "${#p[@]}" in
    1)
      replace "${p[0]}"
      ;;
    2)
      replace "${p[0]}" "${p[0]}"
      ;;
    *)
      ;;
  esac
done < files.txt

popd &>/dev/null
