#!/bin/bash

pushd . &>/dev/null
cd $(dirname $0)

backup_dir=$(pwd)/backup
file_dir=$(pwd)/files

replace() {
  filename=$1
  dest_dir=$2

  case "$#" in
    1)
      dest_dir=~
      ;;
    2)
      ;;
    *)
      exit 1
      ;;
  esac

  # Check the file exists
  if [ ! -f $file_dir/$filename ]; then
    echo "$filename not found!"
    exit 1
  fi

  # Remove old backup and create a new one
  rm $backup_dir/$filename 2>/dev/null
  cp -a $dest_dir/$filename $backup_dir/$filename 2>/dev/null

  # Replace the old file with a symlink to the files
  rm $dest_dir/$filename 2>/dev/null
  ln -s $file_dir/$filename $dest_dir/$filename
}

case "$1" in
  --help|-h)
    echo "options:"
    exit 1
    ;;
esac

mkdir old &>/dev/null

while read p; do
  echo replace $p
  replace $p
done < files.txt

popd &>/dev/null
