#!/bin/bash
pushd . &>/dev/null
cd $(dirname $0)

file_dir=$(pwd)/files

case "$1" in
  --help|-h)
    echo "options:"
    exit 1
    ;;
esac

filename=$(basename $1)
src_dir=$(dirname $1)

if [ "$src_dir" == "." ]; then
  src_dir=~
fi

shift

profileName="default"
commit=false

# parse arguments
while (( "$#" )); do

case "$1" in
  --profile|-p)
    profile=$2
    shift
    ;;
  --commit|-f)
    commit=true
    ;;
  --help|-h)
    echo "options:"
    exit 1
    ;;
esac

shift

done

profile="profiles/$profileName.txt"

# Check the profile exists
if [ ! -f "$profile" ]; then
  echo "$profile not found!"
  exit 1
fi

# Check the file exists in the config
if [ -f $file_dir/$filename ]; then
  echo "$filename is already saved!"
  exit 1
fi

filepath=$src_dir/$filename

# Check the file exists in home
if [ ! -f $filepath ]; then
  echo "$filename source doesn't exists!"
  exit 1
fi

cp $filepath $file_dir/$filename
echo $filename >> $profile

if $commit; then
  git add .
  git commit -m "Add $filename to $profileName"
fi

popd &>/dev/null
