#!/bin/bash
pushd .
cd $(dirname $0)

file_dir=$(pwd)/files

case "$1" in
  --help|-h)
    echo "options:"
    exit 1
    ;;
esac

filename=$1

# Check the file exists in the config
if [ -f $file_dir/$filename ]; then
  echo "$filename is already saved!"
  exit 1
fi

filepath=~/$filename

# Check the file exists in home
if [ ! -f $filepath ]; then
  echo "$filename source doesn't exists!"
  exit 1
fi

cp ~/$filename $file_dir/$filename
echo $filename >> $(pwd)/files.txt

git add .
git commit -m "Add $filename"

popd
